<?php 
/**
 * @file
 * Adds a Facebook feed processor to the Feeds module.
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function feeds_facebook_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_facebook_feeds_plugins() {
  $info = array();
  $info['FeedsFacebookParser'] = array(
    'name' => 'Facebook parser',
    'description' => 'Parse Facebook feeds.',
    'help' => '',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsFacebookParser',
      'file' => 'FeedsFacebookParser.inc',
      'path' => drupal_get_path('module', 'feeds_facebook'),
    ),
  );
  return $info;
}


/* =============================================================================
 *   Video embed field facebook handler override
 * ========================================================================== */

/**
 * Performs alterations on video_embed_field handlers.
 *
 * @param $info
 *   Array of information on video handlers exposed by
 *   hook_video_embed_handler_info() implementations.
 */
function feeds_facebook_video_embed_handler_info_alter(&$info) {
  // Change the function for 'facebook' provider.
  if (isset($info['facebook'])) {
    $info['facebook']['function'] = '_feeds_facebook_handle_video';
  }
}

/**
 * Handler for Facebook videos.
 *
 * @param string $url
 *   The video URL.
 * @param array $settings
 *   The settings array.
 *
 * @return string|bool
 *   The video iframe, or FALSE in case the ID can't be retrieved from the URL.
 */
function _feeds_facebook_handle_video($url, $settings) {
  // Our embed code.
  $embed = '<iframe class="@class" src="https://www.facebook.com/plugins/video.php?href=!id" width="@width" height="@height" ' .
    'style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowfullscreen="true"></iframe> ';

  // Use format_string to replace our placeholders with the settings values.
  $embed = format_string($embed, array(
    '!id' => $url,
    '@width' => $settings['width'],
    '@height' => $settings['height'],
    '@class' => $settings['class'],
  ));

  $video = array(
    '#markup' => $embed,
  );
  return $video;
}

