<?php
/**
 * @file
 * Provides a PDF document class based on the famous TCPDF library that simplifies PDF document generation dramatically.
 */

/**
 * Implements hook_libraries_info().
 */
function tcpdf_document_libraries_info() {
  $libraries['tcpdf'] = array(
    'name' => 'TCPHP based PDF document creation',
    'vendor url' => 'http://www.tcpdf.org/',
    'download url' => 'http://sourceforge.net/projects/tcpdf/files/',
    'version callback' => 'tcpdf_document_get_version',
    'version arguments' => array(
       'file' => 'CHANGELOG.TXT',
       // 6.0.091
       'pattern' => '([0-9\.]+)',
       'lines' => 2,
       'cols' => 20,
    ),
    'files' => array(
       'php' => array(
         'tcpdf.php',
       ),
    ),
  );

  return $libraries;
}

/**
 * Check if the TCPDF library is installed.
 *
 * @return boolean A flag indicating the installed status.
 */
function tcpdf_document_tcpdf_installed() {
  if (($library = libraries_detect('tcpdf')) && !empty($library['installed'])) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Check if the TCPDF library has been loaded.
 *
 * @return boolean A flag indicating the loaded status.
 */
function tcpdf_document_tcpdf_loaded() {
  //
  //  TCPDF library definition and checking functions
  //
  if (!defined('K_TCPDF_EXTERNAL_CONFIG')) {
    define('K_TCPDF_EXTERNAL_CONFIG', TRUE);
  }

  // load external TCPDF configuration
  require_once(dirname(__FILE__).'/tcpdf_document.config.inc');

  // load TCPDF library
  if (($library = libraries_load('tcpdf')) && !empty($library['loaded'])) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Gets the version information from the TCPDF library.
 *
 * @param $library
 *   An associative array containing all information about the library.
 * @param $options
 *   An associative array containing with the following keys:
 *   - file: The filename to parse for the version, relative to the library
 *     path. For example: 'docs/changelog.txt'.
 *   - pattern: A string containing a regular expression (PCRE) to match the
 *     library version. For example: '@version\s+([0-9a-zA-Z\.-]+)@'. Note that
 *     the returned version is not the match of the entire pattern (i.e.
 *     '@version 1.2.3' in the above example) but the match of the first
 *     sub-pattern (i.e. '1.2.3' in the above example).
 *   - lines: (optional) The maximum number of lines to search the pattern in.
 *     Defaults to 20.
 *   - cols: (optional) The maximum number of characters per line to take into
 *     account. Defaults to 200. In case of minified or compressed files, this
 *     prevents reading the entire file into memory.
 *
 * @return
 *   A string containing the version of the library.
 *
 * @see libraries_get_path()
 */
function tcpdf_document_get_version($library, $options) {
  // Provide defaults.
  $options += array(
    'file' => '',
    'pattern' => '',
    'lines' => 20,
    'cols' => 200,
  );

  $file = DRUPAL_ROOT . '/' . $library['library path'] . '/' . $options['file'];
  if (empty($options['file']) || !file_exists($file)) {
    return;
  }
  $file = fopen($file, 'r');
  while ($options['lines'] && $line = fgets($file, $options['cols'])) {
    if (preg_match($options['pattern'], $line, $version)) {
      fclose($file);
      return array_pop($version);
    }
    $options['lines']--;
  }
  fclose($file);
}


/**
 * Ensures that the TCPDF library is loaded, otherwise exits with an error message.
 *
 * If the tcpdf library could be loaded, an instance of a PDFDocument class is created, initialized and returned.
 * The returned PDFDocument instance can be edited with the all available TCPDF class methods and additional
 * methods defined in the class PDFDocument (see class description).
 *
 * @param array  $options
 *        Associative array containing basic settings. All values have a default.
 *        'title' => Title of the document
 *        'subject' => Subject of the document
 *        'author' => Author of the document
 *        'keywords' => Comma separated list of keywords
 *        'header' => Array
 *        'html' => Html code of the header.
 *        'callback' => Document method that generates the header. If 'html' is set, it's ignored.
 *        'textcolor' => Array with rgb-values for header text color, default = array(0,0,0)
 *        'linecolor' => Array with rgb-values for header line color, default = array(0,0,0)
 *        'footer' => Array
 *        'html' => Html code of the footer.
 *        'callback' => Document method that generates the footer. If 'html' is set, it's ignored.
 *        'textcolor' => Array with rgb-values for header text color, default = array(0,0,0)
 *        'linecolor' => Array with rgb-values for header line color, default = array(0,0,0)
 *
 * @param $orientation (string) page orientation. Possible values are (case insensitive):<ul><li>P or Portrait (default)</li><li>L or Landscape</li><li>'' (empty string) for automatic orientation</li></ul>
 * @param $unit (string) User measure unit. Possible values are:<ul><li>pt: point</li><li>mm: millimeter (default)</li><li>cm: centimeter</li><li>in: inch</li></ul><br />A point equals 1/72 of inch, that is to say about 0.35 mm (an inch being 2.54 cm). This is a very common unit in typography; font sizes are expressed in that unit.
 * @param $format (mixed) The format used for pages. It can be either: one of the string values specified at getPageSizeFromFormat() or an array of parameters specified at setPageFormat().
 *
 * @return \obj The created and initialized pdf document.
 */
function tcpdf_document_instance($options = array(), $orientation='P', $unit='mm', $format='A4') {
  // check tcpdf library
  if (!tcpdf_document_tcpdf_loaded()) {
    drupal_set_message('The TCPDF library could not be loaded', 'error');
    return;
  } else {
    // load PDFDocument class
    require_once(dirname(__FILE__).'/tcpdf_document.class.inc');
  }

  // create pdf document
  $pdf = new PDFDocument($orientation, $unit, $format);
  $pdf->InitializeDocument($options);

  return $pdf;
}

