<?php
/**
 * Created by PhpStorm.
 * User: ralph
 * Date: 06.12.16
 * Time: 13:16
 */

/**
 * Defines the Stripe booking platform admin menu path.
 */
define('PXL_SHOP_ADMIN_MENU_PATH', 'admin/pxl_shop');

//
// Loads the shopping cart library
require_once 'includes/pxl_shop.cart.inc';

//
// Loads the product library
require_once 'includes/pxl_shop.product.inc';


/**
 * Session wide data container.
 *
 * @return array Returns the session data array.
 */
function &pxl_shop_session_data() {
  if (!isset($_SESSION['pxl_shop'])) {
    $_SESSION['pxl_shop'] = array();
  }
  return $_SESSION['pxl_shop'];
}


/* =============================================================================
 *   Pxl-shop hooks
 * ========================================================================== */

/**
 * Define the Pixelshop menu as top node of the admin menu.
 * All administration of the Pixelshop platform is added below this menu.
 * @return mixed
 */
function pxl_shop_menu() {
  $items[PXL_SHOP_ADMIN_MENU_PATH] = array(
    'title' => 'Pixelshop',
    'description' => 'Pixel shop - a shopping plattform with integrated Stripe payments.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );

  /* Shopping cart ajax callbacks */
  $items['ajax/pxl-shop/cart-item/%/delete'] = array(
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'pxl_shop_cart_ajax_callback',
    'page arguments' => array(3,4),
  );
  return $items;
}

/**
 * AJAX callback of shopping cart.
 */
function pxl_shop_cart_ajax_callback($item_key, $op) {
  $shopping_cart_empty = false;
  if ($op == 'delete') {
    // delete item(s)
    $shopping_cart_empty = pxl_shop_cart_remove_item($item_key);
  }

  // return availability block, if shopping cart is empty and availability module is enabled
  $block = pxl_shop_block_view('pxl_shop_cart_form');
  if ($shopping_cart_empty && module_exists('pxl_availability')) {
    $block = pxl_availability_block_view('pxl_availability_form');
  }
  drupal_static_reset('drupal_add_js');
  $rendered_block = drupal_render($block);
  $js_settings = array(
    'settings' => drupal_add_js()['settings'],
    'dummy.js' => 0,
  );
  $rendered_js = drupal_get_js('header', $js_settings, true);


  // return block, js already loaded
  drupal_add_http_header('Content-Type', 'text/html; charset=utf-8');
  print $rendered_js;
  print $rendered_block;
  drupal_exit();
}


/**
 * Implements hook_theme().
 */
function pxl_shop_theme($existing, $type, $theme, $path) {
  return array(
    'pxl_shop_cart_form' => array(
      'variables' => array(
        'currency' => null,
        'pay_button_title' => '',
        'pay_button_text' => '',
        'pay_dialog_title' => '',
        'pay_dialog_description' => '',
        'billing_address' => 0,
      ),
      'file' => 'templates/pxl_shop_cart_form.vars.php',
      'template' => 'templates/pxl-shop-cart-form',
    ),
  );
}


/* =============================================================================
 *   Shopping cart Block (Form with cart items table and stripe payment button)
 * ========================================================================== */
/**
 * Implements hook_block_info().
 **/
function pxl_shop_block_info() {
  $blocks['pxl_shop_cart_form'] = array(
    'info' => t('Pixel shopping cart'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}



/**
 * Implements hook_block_configure().
 */
function pxl_shop_block_configure($delta = 0) {
  switch ($delta) {
    case 'pxl_shop_cart_form':
      return _pxl_shop_cart_settings_form($delta);
  }
  return array();
}

function _pxl_shop_cart_settings_form($delta = 0) {
  // define available currencies
  $currencies = array(
    'CHF'  => t('CHF'),
    'EUR' => t('EUR'),
    'USD' => t('USD'),
    'GBP' => t('GBP'),
    'DKK' => t('DKK'),
    'NOK' => t('NOK'),
    'SEK' => t('SEK'),
    'AUD' => t('AUD'),
    'CAD' => t('CAD'),
  );

  $form['pxl_shop'] = array(
    '#type' => 'fieldset',
    '#title' => t('Shopping cart settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#weight' => 0,
  );

  $form['pxl_shop']['currency'] = array(
    '#type' => 'select',
    '#title' => t('Payment currency'),
    '#options' => $currencies,
    '#default_value' => variable_get($delta . '_currency', 'CHF'),
    '#description'   => t('Define the currency of the payment.'),
  );
  $form['pxl_shop']['pay_button_title'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Pay button title'),
    '#default_value' => variable_get($delta . '_pay_button_title', ''),
    '#description'   => t('Define the title of the pay button box. Default: none'),
  );
  $form['pxl_shop']['pay_button_text'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Pay button text'),
    '#default_value' => variable_get($delta . '_pay_button_text', ''),
    '#description'   => t('Define the text of the pay button box. Default: none'),
  );
  $form['pxl_shop']['pay_dialog_title'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Payment dialog title'),
    '#default_value' => variable_get($delta . '_pay_dialog_title', variable_get('site_name')),
    '#description'   => t('Define the company name shown in the payment dialog. Default: Site name'),
  );
  $form['pxl_shop']['pay_dialog_description'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Payment dialog short description'),
    '#default_value' => variable_get($delta . '_pay_dialog_description'),
    '#description'   => t('Define the short description shown in the payment dialog. Default: none'),
  );
  $form['pxl_shop']['billing_address'] = array(
    '#type' => 'checkbox',
    '#title' => t("Collect user's billing address."),
    '#default_value' => variable_get($delta . '_billing_address', false),
    '#description'   => t("Specify whether the payment dialog should collect the user's billing address. Default: false"),
  );
  return $form;
}

/**
 * Implements hook_block_save().
 */
function pxl_shop_block_save($delta = 0, $settings = array()) {
  switch ($delta) {
    case 'pxl_shop_cart_form':
      variable_set($delta . '_currency', $settings['currency']);
      variable_set($delta . '_pay_button_title', $settings['pay_button_title']);
      variable_set($delta . '_pay_button_text', $settings['pay_button_text']);
      variable_set($delta . '_pay_dialog_title', $settings['pay_dialog_title']);
      variable_set($delta . '_pay_dialog_description', $settings['pay_dialog_description']);
      variable_set($delta . '_billing_address', $settings['billing_address']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function pxl_shop_block_view($delta = 0) {
  $block = array();

  switch ($delta) {
    case 'pxl_shop_cart_form':
      $block['subject'] = null;
      $block['content'] = array (
        '#theme' => 'pxl_shop_cart_form',
        '#currency' => variable_get($delta . '_currency'),
        '#pay_button_title' => variable_get($delta . '_pay_button_title'),
        '#pay_button_text' => variable_get($delta . '_pay_button_text'),
        '#pay_dialog_title' => variable_get($delta . '_pay_dialog_title'),
        '#pay_dialog_description' => variable_get($delta . '_pay_dialog_description'),
        '#billing_address' => variable_get($delta . '_billing_address'),
      );
      break;
  }

  return $block;
}


/* =============================================================================
 *   Stripe checkout hooks
 * ========================================================================== */
/**
 * Alters the session parameters with the images of the selected product (apartment)
 * and the cancel and success redirect urls.
 *
 * Checks, if the selected time range for each item in the shopping cart is available.
 * Throws an exception when check for an item fails to prevent payment and booking.

 * @param $session_params
 *
 * @throws \Exception
 */
function pxl_shop_stripe_checkout_session_params_alter(&$session_params) {
  if (!module_exists('pxl_availability')) return;
  //
  // it's guaranteed that only one product is in the shopping cart
  foreach (pxl_shop_cart_items() as $key => $item) {
    if (!pxl_availability_time_range_check($key, $item->start, $item->end)) {
      // remove item from shopping cart
      pxl_shop_cart_remove_item($key);

      // throw not available exception to stop booking
      $startDate = date('d-m-Y H:i T', $item->start);
      $endDate = date('d-m-Y H:i T', $item->end);
      $msg = t('Sorry! Unfortunately a reservation from @start to @end for @name is pending. Try again in a hour', array(
        '@start' => $startDate,
        '@end' => $endDate,
        '@name' => $item->title,
      ));
      throw new Exception($msg);
    }
    else {
      //
      // create a pending calendar event for each item in the shopping cart
      $cal_evt_id = pxl_availability_create_calendar_event_from_cart_item($item);
      $session_params['client_reference_id'] = $cal_evt_id;
      $redirect_url = url('node/' . $key, array('absolute' => TRUE));
      $session_params['success_url'] = $redirect_url;
      $session_params['cancel_url'] = $redirect_url;

      // get product
      $node = node_load($key);
      if (!$node) return;

      // set description for product
      $session_params['description'] = t('@name', ['@name' => $node->title]);

      // get first image urls
      $url = file_create_url($node->field_images[LANGUAGE_NONE][0]['uri']);

      // Localtunnel support, if loacalhost
      if (strpos($url, 'http://localhost') === 0) {
        $url = str_replace('http://localhost', 'https://stripe-checkout.localtunnel.me', $url);
      }
      else if (strpos($url, 'https://localhost') === 0) {
        $url = str_replace('https://localhost', 'https://stripe-checkout.localtunnel.me', $url);
      }
      $session_params['images'][] = $url;
    }
  }
}

/**
 * Implements checkout_session_finished hook.
 *
 * @param $session \Stripe\Checkout\Session
 *
 * @throws \Exception
 */
function pxl_shop_stripe_checkout_session_finished($session) {
  if (!module_exists('pxl_availability')) return;

  //
  // update calendar event as booked
  $item = new stdClass();
  if ($charge = $session->payment_intent->charges->data[0]) {
    $billing_details = $charge->billing_details;
    $item->chargeID = $charge->id;
    $item->name = $billing_details->name;
    $item->email = $billing_details->email;
    $item->address = $billing_details->address->line1 . ' ' . $billing_details->address->line2;
    $item->zip = $billing_details->address->postal_code;
    $item->city = $billing_details->address->city;
    $item->country_code = $billing_details->address->country;
    $item->receipt_url = $charge->receipt_url;
  }
  $cal_evt_id = $session->client_reference_id;
  $cal_evt = pxl_availability_calendar_event_successfully_booked($cal_evt_id, $item);
  $item->description = $cal_evt->body[LANGUAGE_NONE][0]['value'];

  //
  // send email to admin and customer
  global $language;
  $site_mail = variable_get('site_mail');
  $site = explode('@', $site_mail)[1];
  $mail_to = array(
    'admin' => $site_mail,
    'client' => $item->email
  );
  $params['item'] = $item;
  $params['site'] = $site;
  $from = 'reservation@' . $site;

  foreach ($mail_to as $key => $to) {
    drupal_mail('pxl_shop', $key, $to, $language, $params, $from);
  }

}

/**
 * Called by drupal_mail to add specific subject and body of mail.
 *
 * @param $key
 * @param $message
 * @param $params
 */
function pxl_shop_mail($key, &$message, $params) {
  $reservations = array();
  $item = $params['item'];
  $reservations[] = $item->description;

  switch ($key) {
    case 'admin':
      $message['subject'] = t('Notice of online booking made by !customer ...', array('!customer' => $item->name));
      $body_start = array(
        t('ONLINE BOOKING NOTICE!'),
        t("Booking details:\n")
      );
      $body_end = array(
        t("Customer information:"),
        $item->name . '<br>' . $item->address . '<br>' . $item->zip . ' ' . $item->city . '<br>' . $item->country,
        $item->email
      );
      $message['body'] = array_merge($body_start, $reservations, $body_end);
      break;
    case 'client':
      $message['subject'] = t('Confirmation of your booking on !site ...', array('!site' => $params['site']));
      $body_start = array(
        t('Dear !customer', array('!customer' => $item->name)),
        t("you made the following bookings:\n")
      );
      $body_end = array(
        t("\nYou can download a receipt under the following link: @url ", array('@url' => $item->receipt_url)),
        t("\nSincerly yours"),
        t('The !site Team', array('!site' => $params['site'])),
      );
      $message['body'] = array_merge($body_start, $reservations, $body_end);
      break;
  }
}

function pxl_shop_mail_alter(&$message) {
  switch ($message['key']) {
    case 'client':
      $message['subject'] = t('Confirmation of your booking at Grézan Castle Art & Culture ...');
      $body_end = array(
        t('We are looking forward to welcome you soon at Château de Grézan and wish you a pleasant stay.'),
        t("Sincerly yours"),
        t('The Grézan Team')
      );
      $body = $message['body'];
      array_pop($body);
      array_pop($body);
      $message['body'] = array_merge($body, $body_end);
      break;
  }
}
